using System;
using System.Collections.Generic;
using EuropeDominationDemo.Scripts.Enums;
using EuropeDominationDemo.Scripts.Math;
using EuropeDominationDemo.Scripts.Scenarios.Buildings;
using Godot;

namespace EuropeDominationDemo.Scripts.Scenarios.CreatedScenarios;

public class EuropeScenario : Scenario
{
    public override Dictionary<int, CountryData> Countries { get; }
    public sealed override List<ArmyUnitData> ArmyUnits { get; set; }
    public sealed override ProvinceData[] Map { get; set; }
    public sealed override DateTime Date { get; set; }
    public sealed override Image MapTexture { get; set; }

    public EuropeScenario(Image mapTexture)
    {
        MapTexture = mapTexture;

        Date = new DateTime(1444, 11, 12);

        Countries = new Dictionary<int, CountryData>()
        {
            { 0, new CountryData(0, "Great Britain", new Vector3(0.0f, 1.0f, 0.0f), Modifiers.DefaultModifiers()) },
            { 1, new CountryData(1, "France", new Vector3(0.0f, 0.0f, 1.0f), Modifiers.DefaultModifiers()) },
            { 2, new CountryData(2, "Sweden", new Vector3(1.0f, 0.0f, 0.0f), Modifiers.DefaultModifiers()) },
            { 3, new CountryData(3, "Uncolonized", new Vector3(1.0f, 1.0f, 1.0f), Modifiers.DefaultModifiers()) },
            { 4, new CountryData(4, "Wasteland", new Vector3(1.0f, 1.0f, 0.0f), Modifiers.DefaultModifiers()) },
            { 5, new CountryData(5, "Water Wasteland", new Vector3(0.0f, 0.5f, 1.0f), Modifiers.DefaultModifiers()) },
            { 6, new CountryData(6, "Water", new Vector3(0.2f, 0.5f, 1.0f), Modifiers.DefaultModifiers()) }
        };

        Map = new ProvinceData[421]
        {
            new ProvinceData(0, 0, "London", Terrain.Coast, Good.Iron, 1, new float[] { 0, 3 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(1, 0, "London", Terrain.Field, Good.Iron, 3, new float[] { 0, 1 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(2, 0, "London", Terrain.Field, Good.Iron, 1, new float[] { 3, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(3, 0, "London", Terrain.Forest, Good.Iron, 1, new float[] { 0, 3 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(4, 0, "London", Terrain.Plain, Good.Iron, 1, new float[] { 4, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(5, 0, "Paris", Terrain.Plain, Good.Iron, 3, new float[] { 0, 4 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(6, 2, "Lorem", Terrain.Plain, Good.Iron, 3, new float[] { 3, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(7, 2, "FlashBang", Terrain.Plain, Good.Wheat, 1, new float[] { 1, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(8, 2, "CommunistPigs", Terrain.Plain, Good.Wheat, 3, new float[] { 0, 5 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(9, 2, "Berlin", Terrain.Mountains, Good.Wheat, 1, new float[] { 5, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(10, 2, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(11, 1, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(12, 1, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(13, 1, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(14, 1, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(15, 1, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(16, 1, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(17, 1, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(18, 1, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(19, 1, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(20, 1, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(21, 1, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(22, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(23, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(24, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(25, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(26, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(27, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(28, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(29, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(30, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(31, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(32, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(33, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(34, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(35, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(36, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(37, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(38, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(39, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(40, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(41, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(42, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(43, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(44, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(45, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(46, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(47, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(48, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(49, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(50, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(51, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(52, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(53, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(54, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(55, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(56, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(57, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(58, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(59, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(60, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(61, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(62, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(63, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(64, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(65, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(66, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(67, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(68, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(69, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(70, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(71, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(72, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(73, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(74, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(75, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(76, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(77, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(78, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(79, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(80, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(81, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(82, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(83, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(84, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(85, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(86, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(87, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(88, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(89, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(90, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(91, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(92, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(93, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(94, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(95, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(96, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(97, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(98, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(99, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(100, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(101, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(102, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(103, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(104, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(105, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(106, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(107, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(108, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(109, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(110, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(112, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(113, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(114, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(115, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(116, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(117, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(118, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(119, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(120, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(121, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(122, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(122, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(123, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(124, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(125, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(126, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(127, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(128, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(129, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(130, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(131, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(132, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(133, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(134, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(135, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(136, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(137, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(138, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(139, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(140, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(141, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(142, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(143, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(144, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(145, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(146, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(147, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(148, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(149, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(150, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(151, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(152, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(153, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(154, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(155, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(156, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(157, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(158, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(159, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(160, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(161, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(162, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(163, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(164, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(165, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(166, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(167, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(168, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(169, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(170, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(171, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(172, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(173, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(174, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(175, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(176, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(177, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(178, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(179, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(180, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(181, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(182, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(183, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(184, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(185, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(186, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(187, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(188, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(189, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(190, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(191, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(192, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(193, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(194, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(195, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(196, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(197, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(198, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(199, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(200, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(201, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(202, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(203, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(204, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(205, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(206, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(207, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(208, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(209, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(210, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(211, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(212, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(213, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(214, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(215, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(216, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(217, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(218, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(219, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(220, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(221, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(222, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(223, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(224, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(225, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(226, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(227, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(228, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(229, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(230, 4, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(231, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(232, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(233, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(234, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(235, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(236, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(237, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(238, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(239, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(240, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(241, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(242, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(243, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(244, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(245, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(246, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(247, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(248, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(249, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(250, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(251, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(252, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(253, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(254, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(255, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(256, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(257, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(258, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(259, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(260, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(261, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(262, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(263, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(264, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(265, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(266, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(267, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(268, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(269, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(270, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(271, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(272, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(273, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(274, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(275, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(276, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(277, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(278, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(279, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(280, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(281, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(282, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(283, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(284, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(285, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(286, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(287, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(288, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(289, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(290, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(291, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(292, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(293, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(294, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(295, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(296, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(297, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(298, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(299, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(300, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(301, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(302, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(303, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(304, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(305, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(306, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(307, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(308, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(309, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(310, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(311, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(312, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(313, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(314, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(315, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(316, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(317, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(318, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(319, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(320, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(321, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(322, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(323, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(324, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(325, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(326, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(327, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(328, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(329, 3, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(330, 3, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(331, 3, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(332, 3, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(333, 5, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(334, 6, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(335, 6, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(336, 6, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(337, 6, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(338, 6, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(339, 6, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(340, 6, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(341, 6, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(342, 6, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(343, 6, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(344, 6, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(345, 6, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(346, 6, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(347, 6, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(348, 6, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(349, 6, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(350, 6, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(351, 6, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(352, 6, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(353, 6, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(354, 6, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(355, 6, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(356, 6, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(357, 6, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(358, 6, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(359, 6, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(360, 6, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(361, 6, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(362, 6, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(363, 6, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(364, 6, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(365, 6, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(366, 6, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(367, 6, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(368, 6, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(369, 6, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(370, 6, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(371, 6, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(372, 6, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(373, 6, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(374, 6, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(375, 6, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(376, 6, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(377, 6, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(378, 6, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(379, 6, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(380, 6, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(381, 6, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(382, 6, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(383, 6, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(384, 6, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(385, 6, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(386, 6, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(387, 6, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(388, 6, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(389, 6, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(390, 6, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(391, 6, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(392, 6, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(393, 6, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(394, 6, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(395, 6, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(396, 6, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(397, 6, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(398, 6, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(399, 6, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(400, 6, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(401, 6, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(402, 6, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(403, 6, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(404, 6, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(405, 6, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(406, 6, "LibertarianTown", Terrain.Mountains, Good.Wheat, 1, new float[] { 6, 0 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(407, 6, "Liberty", Terrain.Mountains, Good.Wheat, 1, new float[] { 0, 6 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(408, 6, "NY", Terrain.Coast, Good.Wheat, 1, new float[] { 7, 0 }, new List<Building>(),
                Modifiers.DefaultModifiers()),
            new ProvinceData(409, 6, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(410, 6, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(411, 6, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(412, 6, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(413, 6, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(414, 6, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(415, 6, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(416, 6, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(417, 6, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(418, 6, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(419, 6, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
            new ProvinceData(420, 6, "Los Angeles", Terrain.Coast, Good.Wheat, 1, new float[] { 0, 7 },
                new List<Building>(), Modifiers.DefaultModifiers()),
        };

        ArmyUnits = new List<ArmyUnitData>()
        {
            new ArmyUnitData("George Floyd", 1, 3, Modifiers.DefaultModifiers()),
            new ArmyUnitData("Idk", 1, 5, Modifiers.DefaultModifiers()),
            new ArmyUnitData("FunnyName", 1, 6, Modifiers.DefaultModifiers()),
            new ArmyUnitData("Length", 1, 7, Modifiers.DefaultModifiers()),
        };

        Map = GameMath.CalculateBorderProvinces(Map, MapTexture);
        var centers = GameMath.CalculateCenterOfProvinceWeight(MapTexture, Map.Length);
        for (var i = 0; i < Map.Length; i++)
        {
            Map[i].CenterOfWeight = centers[i];
        }
    }
}