using System;
using System.Collections.Generic;
using EuropeDominationDemo.Scripts.Enums;
using EuropeDominationDemo.Scripts.Math;
using EuropeDominationDemo.Scripts.Scenarios.Army;
using EuropeDominationDemo.Scripts.Scenarios.Army.Regiments;
using EuropeDominationDemo.Scripts.Scenarios.Buildings;
using EuropeDominationDemo.Scripts.Scenarios.DiplomacyAgreements;
using EuropeDominationDemo.Scripts.Scenarios.Goods;
using EuropeDominationDemo.Scripts.Scenarios.Goods.Weapon.LandWeapon;
using EuropeDominationDemo.Scripts.Scenarios.ProvinceData;
using EuropeDominationDemo.Scripts.Scenarios.SpecialBuildings;
using EuropeDominationDemo.Scripts.Scenarios.SpecialBuildings.FactoryRecipies;
using Godot;

namespace EuropeDominationDemo.Scripts.Scenarios.CreatedScenarios;

public class EuropeScenario : Scenario
{
    public override Dictionary<int, CountryData> Countries { get; }
    public sealed override ProvinceData.ProvinceData[] Map { get; set; }
    public sealed override DateTime Date { get; set; }
    public sealed override Image MapTexture { get; set; }
    public override Dictionary<int, Vector3> WastelandProvinceColors { get; set; }
    public override Vector3 WaterColor { get; set; }
    public override Vector3 UncolonizedColor { get; set; }

    public override List<Good> Goods { get;}

    public override List<Recipe> Recipes { get; set; }
    public override List<BattleData> Battles { get; set; }


    public EuropeScenario(Image mapTexture)
    {
        Goods = new List<Good>()
        {
            new HarvestedGood(0, "Iron", new Vector3(0.5f, 0.3f, 0.0f)),
            new HarvestedGood(1, "Wheat", new Vector3(0.7f, 0.8f, 0.0f)),
            new HarvestedGood(2, "Wood", new Vector3(0.0f, 0.7f, 0.4f)),
            new InfantryWeapon(3, "Iron Sword", new Vector3(1.0f, 0.2f, 0.3f), 0.01f, 0.01f, 0.0f, 1.0f, Modifiers.DefaultModifiers(additionalTrainingEfficiency: 1.3f), 10)
        };
        
        
        
        MapTexture = mapTexture;

        Date = new DateTime(1444, 11, 12);
        

        Countries = new Dictionary<int, CountryData>()
        {
            { 0, new CountryData(0, "Great Britain", new Vector3(0.0f, 1.0f, 0.0f), Modifiers.DefaultModifiers(), 100, 300, new List<General>(), new List<Admiral>(), new List<UnitData>(), new List<Template>(), new Dictionary<int, List<DiplomacyAgreement>>())},
            { 1, new CountryData(1, "France", new Vector3(0.0f, 0.0f, 1.0f), Modifiers.DefaultModifiers(), 200, 200,new List<General>(), new List<Admiral>(), new List<UnitData>(), new List<Template>(), new Dictionary<int, List<DiplomacyAgreement>>()) },
            { 2, new CountryData(2, "Sweden", new Vector3(1.0f, 0.0f, 0.0f), Modifiers.DefaultModifiers(), 300, 100,new List<General>(), new List<Admiral>(), new List<UnitData>(), new List<Template>(), new Dictionary<int, List<DiplomacyAgreement>>()) },
        };
        WastelandProvinceColors = new Dictionary<int, Vector3>()
        {
            { 230, new Vector3(1.0f, 1.0f, 0.0f) },
            { 333, new Vector3(0.0f, 0.5f, 1.0f) }
        };
        WaterColor = new Vector3(0.2f, 0.5f, 1.0f); 
        UncolonizedColor = new Vector3(0.7f, 1.0f, 1.0f);

        Recipes = new List<Recipe>()
        {
            new(new Dictionary<Good, double>(){
                { Goods[0], 1 },
                { Goods[2] , 0.5 }
            }, Goods[3])
        };

        Battles = new List<BattleData>();
        
        

        Map = new ProvinceData.ProvinceData[421]
        {
            new LandColonizedProvinceData(0, 0, "London", Terrain.Coast, Goods[0], 10, Good.DefaultGoods(),
                new List<Building>(),
                Modifiers.DefaultModifiers(), new SpecialBuilding[3] {null, null, null}, null),
            new LandColonizedProvinceData(1, 0, "London", Terrain.Field, Goods[2], 20, Good.DefaultGoods(),
                new List<Building>(),
                Modifiers.DefaultModifiers(), new SpecialBuilding[3] {null, null, null}, null),
            new LandColonizedProvinceData(2, 0, "London", Terrain.Field, Goods[2], 30, Good.DefaultGoods(),
                new List<Building>(),
                Modifiers.DefaultModifiers(), new SpecialBuilding[3] {null, null, null}, null),
            new LandColonizedProvinceData(3, 0, "London", Terrain.Forest, Goods[0], 30, Good.DefaultGoods(),
                new List<Building>(),
                Modifiers.DefaultModifiers(), new SpecialBuilding[3] {null, null, null}, null),
            new LandColonizedProvinceData(4, 0, "London", Terrain.Plain, Goods[0], 30, Good.DefaultGoods(),
                new List<Building>(),
                Modifiers.DefaultModifiers(), new SpecialBuilding[3] {null, null, null}, null),
            new LandColonizedProvinceData(5, 0, "Paris", Terrain.Plain, Goods[0], 30, Good.DefaultGoods(), new List<Building>(),
                Modifiers.DefaultModifiers(), new SpecialBuilding[3] {null, null, null}, null),
            new LandColonizedProvinceData(6, 2, "Lorem", Terrain.Plain, Goods[0], 30, Good.DefaultGoods(), new List<Building>(),
                Modifiers.DefaultModifiers(), new SpecialBuilding[3] {null, null, null}, null),
            new LandColonizedProvinceData(7, 2, "FlashBang", Terrain.Plain, Goods[1], 1, Good.DefaultGoods(),
                new List<Building>(), Modifiers.DefaultModifiers(), new SpecialBuilding[3] {null, null, null}, null),
            new LandColonizedProvinceData(8, 2, "CommunistPigs", Terrain.Plain, Goods[1], 3, Good.DefaultGoods(),
                new List<Building>(), Modifiers.DefaultModifiers(), new SpecialBuilding[3] {null, null, null}, null),
            new LandColonizedProvinceData(9, 2, "Berlin", Terrain.Mountains, Goods[1], 1, Good.DefaultGoods(),
                new List<Building>(), Modifiers.DefaultModifiers(), new SpecialBuilding[3] {null, null, null}, null),
            new LandColonizedProvinceData(10, 2, "LibertarianTown", Terrain.Mountains, Goods[1], 1, Good.DefaultGoods(),
                new List<Building>(), Modifiers.DefaultModifiers(), new SpecialBuilding[3] {null, null, null}, null),
            new LandColonizedProvinceData(11, 1, "Liberty", Terrain.Mountains, Goods[1], 1, Good.DefaultGoods(),
                new List<Building>(), Modifiers.DefaultModifiers(), new SpecialBuilding[3] {null, null, null}, null),
            new LandColonizedProvinceData(12, 1, "NY", Terrain.Coast, Goods[1], 1, Good.DefaultGoods(), new List<Building>(),
                Modifiers.DefaultModifiers(), new SpecialBuilding[3] {null, null, null}, null),
            new LandColonizedProvinceData(13, 1, "Los Angeles", Terrain.Coast, Goods[1], 1, Good.DefaultGoods(),
                new List<Building>(), Modifiers.DefaultModifiers(), new SpecialBuilding[3] {null, null, null}, null),
            new LandColonizedProvinceData(14, 1, "LibertarianTown", Terrain.Mountains, Goods[1], 1, Good.DefaultGoods(),
                new List<Building>(), Modifiers.DefaultModifiers(), new SpecialBuilding[3] {null, null, null}, null),
            new LandColonizedProvinceData(15, 1, "Liberty", Terrain.Mountains, Goods[1], 1, Good.DefaultGoods(),
                new List<Building>(), Modifiers.DefaultModifiers(), new SpecialBuilding[3] {null, null, null}, null),
            new LandColonizedProvinceData(16, 1, "NY", Terrain.Coast, Goods[1], 30, Good.DefaultGoods(), new List<Building>(),
                Modifiers.DefaultModifiers(), new SpecialBuilding[3] {null, null, null}, null),
            new LandColonizedProvinceData(17, 1, "Los Angeles", Terrain.Coast, Goods[1], 1, Good.DefaultGoods(),
                new List<Building>(), Modifiers.DefaultModifiers(), new SpecialBuilding[3] {null, null, null}, null),
            new LandColonizedProvinceData(18, 1, "LibertarianTown", Terrain.Mountains, Goods[1], 1, Good.DefaultGoods(),
                new List<Building>(), Modifiers.DefaultModifiers(), new SpecialBuilding[3] {null, null, null}, null),
            new LandColonizedProvinceData(19, 1, "Liberty", Terrain.Mountains, Goods[1], 1, Good.DefaultGoods(),
                new List<Building>(), Modifiers.DefaultModifiers(), new SpecialBuilding[3] {null, null, null}, null),
            new LandColonizedProvinceData(20, 1, "NY", Terrain.Coast, Goods[1], 1, Good.DefaultGoods(), new List<Building>(),
                Modifiers.DefaultModifiers(), new SpecialBuilding[3] {null, null, null}, null),
            new LandColonizedProvinceData(21, 1, "Los Angeles", Terrain.Coast, Goods[1], 1, Good.DefaultGoods(),
                new List<Building>(), Modifiers.DefaultModifiers(), new SpecialBuilding[3] {null, null, null}, null),
            new UncolonizedProvinceData(22, "DefaultName", Terrain.Forest, Goods[1], Modifiers.DefaultModifiers()),
            new LandColonizedProvinceData(23, 0, "London", Terrain.Coast, Goods[0], 10, Good.DefaultGoods(),
                new List<Building>(),
                Modifiers.DefaultModifiers(), new SpecialBuilding[3] {null, null, null}, null),
            new UncolonizedProvinceData(24, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(25, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(26, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(27, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(28, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(29, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(30, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(31, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(32, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(33, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(34, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(35, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(36, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(37, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(38, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(39, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new LandColonizedProvinceData(40, 0, "London", Terrain.Coast, Goods[0], 10, Good.DefaultGoods(),
                new List<Building>(),
                Modifiers.DefaultModifiers(), new SpecialBuilding[3] {null, null, null}, null),
            new UncolonizedProvinceData(41, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(42, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(43, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(44, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(45, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(46, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(47, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(48, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(49, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(50, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(51, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(52, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(53, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(54, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(55, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(56, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(57, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(58, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(59, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(60, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(61, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(62, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(63, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(64, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(65, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(66, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(67, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(68, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(69, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(70, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(71, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(72, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(73, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(74, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(75, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(76, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(77, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(78, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(79, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(80, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(81, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(82, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(83, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(84, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(85, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(86, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(87, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(88, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(89, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(90, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(91, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(92, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(93, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(94, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(95, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(96, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(97, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(98, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(99, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(100, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(101, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(102, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(103, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(104, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(105, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(106, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(107, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(108, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(109, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(110, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(111, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(112, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(113, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(114, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(115, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(116, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(117, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(118, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(119, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(120, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(121, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(122, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(123, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(124, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(125, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(126, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(127, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(128, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(129, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(130, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(131, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(132, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(133, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(134, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(135, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(136, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(137, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(138, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(139, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(140, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(141, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(142, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(143, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(144, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(145, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(146, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(147, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(148, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(149, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(150, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(151, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(152, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(153, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(154, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(155, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(156, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(157, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(158, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(159, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(160, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(161, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(162, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(163, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(164, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(165, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(166, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(167, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(168, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(169, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(170, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(171, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(172, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(173, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(174, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(175, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(176, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(177, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(178, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(179, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(180, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(181, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(182, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(183, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(184, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(185, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(186, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(187, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(188, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(189, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(190, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(191, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(192, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(193, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(194, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(195, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(196, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(197, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(198, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(199, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(200, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(201, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(202, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(203, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(204, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(205, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(206, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(207, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(208, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(209, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(210, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(211, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(212, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(213, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(214, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(215, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(216, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(217, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(218, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(219, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(220, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(221, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(222, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(223, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(224, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(225, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(226, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(227, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(228, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(229, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new WastelandProvinceData(230, "DefaultName"),
            new UncolonizedProvinceData(231, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(232, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(233, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(234, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(235, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(236, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(237, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(238, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(239, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(240, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(241, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(242, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(243, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(244, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(245, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(246, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(247, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(248, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(249, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(250, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(251, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(252, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(253, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(254, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(255, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(256, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(257, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(258, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(259, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(260, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(261, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(262, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(263, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(264, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(265, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(266, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(267, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(268, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(269, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(270, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(271, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(272, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(273, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(274, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(275, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(276, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(277, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(278, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(279, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(280, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(281, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(282, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(283, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(284, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(285, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(286, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(287, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(288, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(289, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(290, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(291, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(292, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(293, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(294, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(295, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(296, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(297, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(298, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(299, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(300, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(301, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(302, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(303, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(304, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(305, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(306, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(307, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(308, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(309, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(310, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(311, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(312, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(313, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(314, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(315, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(316, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(317, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(318, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(319, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(320, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(321, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(322, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(323, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(324, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(325, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(326, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(327, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(328, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(329, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(330, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(331, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new UncolonizedProvinceData(332, "DefaultName", Terrain.Forest, Goods[0], Modifiers.DefaultModifiers()),
            new WastelandProvinceData(333, "DefaultName"),
            new SeaProvinceData(334, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(335, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(336, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(337, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(338, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(339, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(340, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(341, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(342, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(343, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(344, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(345, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(346, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(347, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(348, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(349, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(350, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(351, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(352, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(353, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(354, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(355, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(356, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(357, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(358, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(359, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(360, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(361, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(362, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(363, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(364, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(365, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(366, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(367, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(368, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(369, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(370, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(371, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(372, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(373, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(374, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(375, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(376, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(377, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(378, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(379, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(380, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(381, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(382, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(383, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(384, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(385, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(386, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(387, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(388, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(389, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(390, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(391, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(392, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(393, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(394, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(395, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(396, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(397, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(398, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(399, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(400, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(401, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(402, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(403, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(404, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(405, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(406, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(407, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(408, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(409, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(410, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(411, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(412, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(413, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(414, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(415, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(416, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(417, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(418, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(419, "BlackSea", Modifiers.DefaultModifiers()),
            new SeaProvinceData(420, "BlackSea", Modifiers.DefaultModifiers()),
        };

        Map = GameMath.CalculateBorderProvinces(Map, MapTexture);
        var centers = GameMath.CalculateCenterOfProvinceWeight(MapTexture, Map.Length);
        for (var i = 0; i < Map.Length; i++)
        {
            Map[i].CenterOfWeight = centers[i];
        }
    }
}